---
- hosts: pt
  connection: local
  gather_facts: True
  roles:
    - { role: scalets }

- hosts: pt
  gather_facts: False
  roles:
    - { role: packages }

- hosts: pt
  roles:
    - { role: docker }

- hosts: pt
  roles:
    - { role: ufw }
