---
- name: Install packages
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - htop
    - tree
    - vim
    - ufw
    - apt-transport-https
    - ca-certificates
