---
- name: Add SSH key to Vscale account
  run_once: true
  vscale_ssh:
    token: "{{ vscale_token }}"
    name: "Ansible"
    public_key: "{{ key }}"
    state: present

- name: Create scalet for inventory hosts
  vscale_scalets:
    token: "{{ vscale_token }}"
    name: "{{ inventory_hostname }}"
    plan: small
    location: spb0
    image: ubuntu_14.04_64_002_master
    key_name: "Ansible"
    collect_facts: "yes"
    power_state: "started"
    upgrade: "yes"
    state: present
  register: server

- set_fact:
    ansible_ssh_host: "{{ server['scalet']['public_address']['address'] }}"
