---
- name: Install docker-py
  pip:
    name=docker-py 
    state=present
    version=1.1.0
- name: Add docker apt repo
  apt_repository:
    repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main'
    state=present

- name: Import the Docker repository key
  apt_key:        
    keyserver=hkp://p80.pool.sks-keyservers.net:80
    id=58118E89F3A912897C070ADBF76221572C52609D

- name: Install Docker package
  apt:
    name=docker-engine
    update_cache=yes

# - name: Create a docker group
#   group: 
#       name=docker 
#       state=present

# - name: Add user(s) to docker group
#   user: 
#       name={{ item }} 
#       group=docker 
#       state=present
#   with_items: docker_users
#   when: docker_users is defined

- name: Configure Docker 
  template: 
      src=default_docker.j2 
      dest=/etc/default/docker 
      mode=0644 
      owner=root 
      group=root
  notify: systemctl restart docker
